name: aws-lambda-haskell-runtime
version: 1.1.0
github: "theam/aws-lambda-haskell-runtime"
license: Apache-2.0
author: Nikita Tchayka
maintainer: hackers@theagilemonkeys.com
copyright: 2018 The Agile Monkeys SL

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: Haskell runtime for AWS Lambda
category: AWS
description: Please see the README on GitHub at <https://github.com/theam/aws-lambda-haskell-runtime#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  dependencies:
    - aeson
    - bytestring
    - http-client
    - http-types
    - optparse-generic
    - process
    - template-haskell
    - text
    - uuid
    - safe-exceptions-checked
    - path
    - path-io
  source-dirs: src
  exposed-modules:
    - Aws.Lambda
    - Aws.Lambda.Runtime

executables:
  bootstrap:
    source-dirs: app
    main: Main.hs
    dependencies:
      - aws-lambda-haskell-runtime
      - http-client

tests:
  aws-lambda-haskell-runtime-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec

default-extensions:
  - TemplateHaskell
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - DeriveGeneric
  - TypeApplications
  - FlexibleContexts
  - DeriveAnyClass
  - QuasiQuotes

ghc-options:
  - -Wall
  - -fno-warn-orphans
  - -optP-Wno-nonportable-include-path
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wcompat
  - -Widentities
  - -Wredundant-constraints
  - -Wmissing-export-lists
  - -Wpartial-fields
  - -fhide-source-paths
  - -freverse-errors
  - -O2
